### ISSUE TITLE
Milnesium release planning [old]

### ISSUE THREAD

**Issue by cwgoes** [heliaxdev/juvix#542]
Rough target: mid-Feb.

Major features

- [ ] First version of proof UX (ref https://github.com/metastatedev/juvix/issues/518) (@cyberglot)
- [ ] Coverage checking (@thealmarty)
- [ ] Datatypes + pattern matching to Michelson (@cwgoes @thealmarty @mariari)
- [ ] First version of (simple) unification (@andy-morris)
- [ ] First version of the REPL (ref https://github.com/metastatedev/juvix/issues/534) (@mariari)

Minor features / cleanup

- [ ] Pass full context all the way to backends - https://github.com/metastatedev/juvix/issues/531
- [ ] Parameterisation clean-up - https://github.com/metastatedev/juvix/issues/506
- [ ] Typechecker needs to annotate globals - https://github.com/metastatedev/juvix/issues/495
- [ ] Pattern matching in terms - https://github.com/metastatedev/juvix/issues/536
