### ISSUE TITLE
Florarctus Release Planning

### ISSUE THREAD

**Issue by mariari** [heliaxdev/juvix#779]
Target Date: June 10th

### Release Goals
- [ ] [1/2] Arithmetic circuit (@Acentelles)
  -  [ ] Algebraic Data Types 
  -  [X] Basic Backend #795  
- [x] Effect handlers syntax parsing (@cyberglot) #722
- [ ] ANF translation of effect handlers (@cyberglot) #787 
- [ ] Formulation of Passes in terms of a Typed Generator #796 (@cyberglot, @mariari)
- [ ] Records #754 (@Acentelles, @andy-morris)
- [x] Algebraic data types #754 (@Acentelles)
- [ ] Fix nesting issues with terms 3 or greater #755 (@Acentelles, @andy-morris , @mariari) 
- [ ] Minimal LLVM release #778 (@systemf-frank)
- [ ] More Pipeline clean up (@systemf-frank)
- [ ] [0/2] Less important but good subgoals to shoot for
  - [ ] Annotations/Documentation through Core (@mariari, everyone)
 
### Previous Release

[Milneisum release planning](#693)
